### ISSUE TITLE
How do we mix testcontainers, mysql & flyway

### ISSUE THREAD

**Issue by hendisantika** [maheshwarLigade/TestContainerDemo#1]
How do we mix testcontainers, mysql & flyway?

**Comment by maheshwarLigade** [comment]
@hendisantika  I haven't tried on this integration but there are articles available on this, kindly check
https://flywaydb.org/documentation/database/testcontainers

**Comment by hendisantika** [comment]
HI @maheshwarLigade . Finally, I already fixed that.
Thanks by the way.
